version: '3.8'

services:
  db:
    image: postgres:16.1 # It is best practice to use a specific version tag
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser # Optional: sets a custom user name
      POSTGRES_DB: mydatabase # Optional: creates a custom database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
